# Generated by Django 3.1.4 on 2022-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_wxid', models.CharField(default='', max_length=255, verbose_name='机器人微信id')),
                ('val_type', models.CharField(default='', max_length=255, verbose_name='配置的值类型（string字符串,array数组,object对象）')),
                ('key', models.CharField(default='', max_length=255, verbose_name='配置唯一key')),
                ('val', models.CharField(default='', max_length=4000, verbose_name='值')),
                ('desc', models.CharField(default='', max_length=4000, verbose_name='配置描述')),
            ],
            options={
                'verbose_name': '机器人配置表',
                'verbose_name_plural': '机器人配置表',
                'db_table': 'bot_config',
            },
        ),
    ]
